export const ERROR_MESSAGES = {
    MISSING_FIELDS: "Missing required fields",
    USER_EXISTS: "User already exists",
    USER_NOT_FOUND: "User not found",
    INVALID_USER_ID: "Invalid user ID",
    REQUEST_BODY_MISSING: "Request body is missing",
    INCORRECT_PASSWORD: "Incorrect password",
    COULD_NOT_LOG_OUT: "Could not log out",
    UNAUTHORIZED_NO_SESSION: "Unauthorized: No active session",
    UNAUTHORIZED_USER_NOT_FOUND: "Unauthorized: User not found",
    SERVER_ERROR: "Server error",
    POST_NOT_FOUND: "Post not found",
    COMMENT_NOT_FOUND: "Comment not found",
    INVALID_COMMENT_ID: "Invalid comment ID",
    USER_ALREADY_LIKED_POST: "User already liked this post",
    LIKE_NOT_FOUND: "Like not found or user did not like this post",
    CONTENT_REQUIRED: "Content is required",
    INVALID_POST_ID: "Invalid post ID",
    FORBIDDEN_EDIT_POST: "Forbidden: you can only edit your own posts",
    FORBIDDEN_DELETE_POST: "Forbidden: you are not authorized to delete this post",
};
